services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

  db:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  db_data: